sudo: required
services:
  - docker
language: go
go:
  - '1.13.3'
before_install:
  - go get ./...
script:
  - go build main.go
  - go build -o jenkins-scheduler main.go
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t ${DOCKER_USER}/jenkins-scheduler:$TRAVIS_COMMIT .
  - docker tag ${DOCKER_USER}/jenkins-scheduler:$TRAVIS_COMMIT ${DOCKER_USER}/jenkins-scheduler:latest
  - docker push ${DOCKER_USER}/jenkins-scheduler:$TRAVIS_COMMIT
  - docker push ${DOCKER_USER}/jenkins-scheduler:latest
env:
  global:
    - DOCKER_USER=amrfarid
