sudo: required
services:
  - docker
language: go
go:
  - '1.13.3'
before_install:
  - go get ./...
script:
  - go build main.go
  - go build -o jenkins-scheduler main.go

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push ${DOCKER_USER}/jenkins-scheduler:$TRAVIS_COMMIT
env:
  global:
    - DOCKER_USER=amrfarid
